#!/usr/bin/env bash
CWD=$(pwd)

set -a
source ".env"
set +a

echo $BUGSNAG_API_KEY

curl -X POST https://upload.bugsnag.com/ -F apiKey=$BUGSNAG_API_KEY \
 -F sourceMap=@build/index.js.map \
 -F minifiedFile=@build/index.js \
 -F minifiedUrl=http://localhost:3000/* \
 -F projectRoot=$CWD \
 -F overwrite=true \

