#!/usr/bin/env bash

# setup default .env file
if [ ! -f ../.env ]
then
  cp ../.env.example ../.env
fi

# initialize public schema
prisma/prisma-migrate-dev public public

# generate prisma client for public and tenant schemas
prisma/prisma-generate public
prisma/prisma-generate tenant
